### ISSUE TITLE
New Feature (GIF Tag)

### ISSUE THREAD

**Issue by rzhe97** [UtarSccGroupProject/html#18]
I would like to suggest the development team to develop a built-in GIF Tag for user to put GIF that without much trouble.

**Comment by leongjiameng** [comment]
Okay, I will handle this new feature development. Thanks for the suggestion.

**Comment by leongjiameng** [comment]
Please refer PR #17  for this new feature.
The issue will be closed.
Many thanks.
Please create a new issue if you still have any suggestion.
